### ISSUE TITLE
Слишком маленькая задержка между запросами

### ISSUE THREAD

**Issue by httsmvkcom** [bussy1/auto-smile#1]
Привет всем! Обнаружил небольшую ошибку. Разница между запросами - 0.1 секунда что слишком мало и из-за этого появляется ошибка VK Api "Too many requests per second" 
Я заменил на 0.250 секунд и избавился от подобных ошибок. 
Прошу автора сделать тоже самое

**Comment by bussy1** [comment]
Спасибо я исправлю!
